version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tftle
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080