package com.wordl.tftle.champion;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
public class ChampionController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ChampionRepository championRepository;

    @Autowired
    private ChampionService championService;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Champion> getAllChampions() {
        // This returns a JSON or XML with the users
        return championRepository.findAll();
    }

    @GetMapping(path="/winner")
    public @ResponseBody Champion getWinnerChampion() {
        // This returns a JSON or XML with the users
        return championService.getWinner();
    }
}
